### PR TITLE
fix(group): Check for uniqueness only using group name

### LINKED ISSUE #80: Uniqueness of groups are not determined correctly
Currently, we determine uniqueness of groups using the `Group::equals` method, which compares name and tags. We should determine this using only the name instead.

### PR DESCRIPTION
**Pull request by zwliew**
Fixes #80

Compared to checking every field, check only the group name.

### CODE REVIEW

File: src/main/java/seedu/address/model/group/UniqueGroupList.java [hunk 1]
```diff
@@ -108,11 +108,10 @@ public boolean equals(Object other) {
         }
 
         // instanceof handles nulls
-        if (!(other instanceof UniqueGroupList)) {
+        if (!(other instanceof UniqueGroupList otherUniqueGroupList)) {
```
Comment (dexterkwxn) [inline src/main/java/seedu/address/model/group/UniqueGroupList.java:111]: wow im learning something new about java every day.

**Review by dexterkwxn — APPROVED** [review]
