### PR TITLE
Fix issue with Group name validation

### LINKED ISSUE #128: Unexpected exception when attempting to edit a group name
Reproduction steps:
1. `add-group` a group with some name X.
2. `edit-group` the group to have some valid name Y.

Result: the application internally encounters throws an IllegalArgumentException, but no visible error is shown in the UI.
Expected: No error, and the UI shows success.

Note: the exception states: `Caused by: java.lang.IllegalArgumentException: Group names should be alphanumeric`.

### LINKED ISSUE #150: Incorrect help message for `add-assignment` and `delete-assignment`
Related to #136 

Image

Image

### LINKED ISSUE #152: add-group raises wrong Message Constraint
when running a add-group with an invalid name `add-group n/()*&^%$` 
the Message_Constraint from `Name` class shows up instead of the intended one from `Group` class.

validation regex used for add-group is also wrong. It uses the `Name` class on instead of the `Group` class.

related to #136 and #128

### PR DESCRIPTION
**Pull request by lyhthaddeus**
fixes #128 
fixes #152 
fixes #150

Most of the issue stem from non standardized use of `ParserUtil`. This led to messy and hard to follow code logic for Group Name validation.

Fix: Create a `parseGroupName` method in `ParseUtil` class and ensure all string parsing would be done through either `parseName` or `parseGroupName`.

This ensures that validation checks for all string will be performed and all error thrown can be caught by ui effectively.

Additional: 
* Might want to reconsider the regex check for groupName as some special characters such as `-` or `()` makes sense for groupName.
* Might want to consider adding the same validation for Assignment if not similar issue may arise in the future.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java [hunk 1]
```diff
@@ -37,7 +37,10 @@ public EditGroupCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
                     EditGroupCommand.MESSAGE_USAGE), ive);
         }
-        String newGroupName = argMultimap.getValue(PREFIX_NAME).orElse("");
+        String newGroupName = "";
+        if (argMultimap.getValue(PREFIX_NAME).isPresent()) {
+            newGroupName = ParserUtil.parseGroupName(argMultimap.getValue(PREFIX_NAME).get());
+        }
```
Comment (zwliew) [inline src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java]: If the user supplies no group name (i.e. they omit the g/ parameter), would this cause the group to have an empty name? I think it would, and that is a problem. We should use a null value instead, and possibly even follow what Person does with the EditPersonDescriptor

**Review by zwliew — CHANGES_REQUESTED** [review]

**Review by zwliew — APPROVED** [review]
I'll fix the issues later in another PR
