### PR TITLE
fix: Fix most code-related and some doc-related bug reports

### LINKED ISSUE #173: [PE-D][Tester A] User Guide: Mismatch between Order of Commands in Command Summary and Feature List
In the feature list of the User Guide, the `help` command is listed above all other commands:

However, it is listed below almost all commands in the command summary:

Aside from this instance of a mismatch, the other commands are listed in the same order in the feature list and in the command summary. This may make it slightly jarring for readers, who may expect the `help` command at the top of the command summary.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AerollingOverDeepBlueSeas/ped#1

### LINKED ISSUE #174: [PE-D][Tester E] Group tag cannot be edited
command in the following form does not work: edit-group INDEX t/TAG  and trigger the following exception:

This command is legal according to UG

Editing the name of a group alone, or both name and tag works though.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Taoseeker/ped#1

### LINKED ISSUE #176: [PE-D][Tester E] Documentation description typo
Instead of "persons matching at least one keyword will be returned" shouldn't it be "groups matching.....".

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: Taoseeker/ped#2

### LINKED ISSUE #179: [PE-D][Tester A] User Guide: Unusual Order of Assignment-Related Commands
The order of commands/ features presented in the User Guide are consistent and logical, which provides a clear flow to the readers. However, there is a slight anomaly in the arrangement of the assignment-related commands (add, edit, delete) compared to the person and group related commands (add, delete, edit). 
 

Rearranging the assignment-related commands (or using the add, edit, delete order for all commands) may help readers navigate the User Guide more easily, as they can get a better idea where to expect the information about the commands to be placed in relation to each other. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AerollingOverDeepBlueSeas/ped#2

### LINKED ISSUE #180: [PE-D][Tester C] Allowed to add 2 different name with the same phone number
Command executed used

`add n/Bill  p/98765432 e/bill@gmail.com a/test t/friends`
`add n/Jack p/98765432 e/bill@gmail.com a/test t/friends`

The app allows the usage of 2 different name but with 2 same phone number. This might be an issue if the user accidentally wrote the same phone number, leading to confusion. Perhaps making phone number unique might be better

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: CJ-783/ped#2

### LINKED ISSUE #182: [PE-D][Tester B] No Error handling for Phone Number Length
When using the add command, there is no checks for the validity of the phone number beyond just a length of 3 minimally. I can add an infinitely long phone number under the field "p". Perhaps a check to handle a valid phone number could be useful here.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Ben926/ped#1

### LINKED ISSUE #183: [PE-D][Tester D] Confusing phrasing about the compulsory/optional fields in User Guide
These two pointers shown in the screenshot are contradicting. Compulsory fields are defined as "items in `UPPER_CASE`, but optional fields seem to be in upper case as well (e.g., `[t/TAG]`). How about combining the two lines to say only items in square brackets are optional, others are compulsory?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: OvOtter/ped#3

### LINKED ISSUE #185: [PE-D][Tester B] Unclear Explanation of Data Architecture in UG
User guide contains no information about the data architecture of the project. It is just quick start and then the commands. It was very confusing how theres groups, assignments, attendances and took a while to understand how these 3 are related. Adding a diagram to show how this works or a simple explanation about how these new fields relate to each other would be helpful.

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Ben926/ped#2

### LINKED ISSUE #191: [PE-D][Tester B] UG has no specified value proposition for the target userr
Although the target user is specified as teaching assistants, it is not mentioned what exactly this app offers them. Is this for managing tutorials specifically, grading work etc.?  It merely shows the command summary straightaway. Some value proposition about what this app is useful for specifically would be useful.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: Ben926/ped#4

### LINKED ISSUE #192: [PE-D][Tester C] Confusion with prefix
Different command utilize different prefixes.

For example, the add command utilizes `n/` prefix when adding a name. However, `add-to-group` utilizes `P/` instead, and then phone numbers are `p/`.

This is quite confusing and will impede my typing speed. Perhaps standardizing all the prefix throughout the command might be better

This is especially more confusing when I realised that certain prefix utilized caps, and certain doesn't

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: CJ-783/ped#6

### LINKED ISSUE #193: [PE-D][Tester E] Change caused by editing a person is not captured by the group that person belongs to
Edited the person name from Lekang to Ben.

The person's name is properly changed in the preview of the group.

But after input show-group-details commands, the person name is not changed.

For debugging, I noted that when I update the details of a group using edit-group INDEX n/NAME (I did not include a tag), the show-group-details content will update accordingly.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Taoseeker/ped#4

### LINKED ISSUE #197: [PE-D][Tester C] Person is caps sensitive in add-to-group command
When adding a user to a group, took me awhile to realise that it is case sensitive as the user guide did not state under this specific command. 

Perhaps it might be better to also update the user-guide to include this

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: CJ-783/ped#8

### LINKED ISSUE #199: [PE-D][Tester E] Attendance not updated immediately in show-group-details
When the content currently shown is the group detail of group 2, using following command to mark attendance of Ben in Group 2,
mark-attendance P/Ben g/2 w/1

marking attendance of persons in the group will not be immediately reflected in the show-group-details view. User have to call show-group-details again to see the updated details.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: Taoseeker/ped#5

### LINKED ISSUE #202: [PE-D][Tester D] Unnecessary repetition on explaining optional fields
The "Tip" box here might be unnecessary as optional fields have been clearly explained in the command format at the begining of the same Feature section.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: OvOtter/ped#5

### LINKED ISSUE #204: [PE-D][Tester C] Doesn't automatically update group
After running the command

`delete-from-group P/yu g/test`, the list doesn't automatically update and might lead to confusion.

Perhaps refreshing the list after the user has typed the command might be a good idea.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: CJ-783/ped#9

### LINKED ISSUE #205: [PE-D][Tester E] Command format inconsistency
The prefix for PERSON_NAME is P/ which uses upper case, while it is understandable since the lowercase prefix is taken by phone, would it be better use n/NAME in command? This will not cause ambiguity since the group name uses another prefix g/ (just like what is done to add-assignment)

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Taoseeker/ped#6

### LINKED ISSUE #206: [PE-D][Tester A] User Guide: Minor Grammar/ Wording Nitpicks
These are minor grammar/ wording nitpicks that I have decided to place in a single issue, as they feel too minor to be given multiple bug reports.

1. This is a legacy grammar issue left over from the Quick Start section of the AB3 UG:

2. There is a slight inconsistency in the tag name used for "friend", as both `friend` and `friends` are used in the User Guide. The screenshot below is taken from examples of the `add` command. Please ignore this nitpick if it is not intentional. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AerollingOverDeepBlueSeas/ped#6

### LINKED ISSUE #207: [PE-D][Tester B] show-group-details output does not format Person object properly
When using show-group-details command, the members are not displayed in proper string format, but as seedu.address.model.person.Person{name=...}. 

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Ben926/ped#9

### LINKED ISSUE #208: [PE-D][Tester C] Allow to add Invalid phone number
I'm able to add weird phone number. Perhaps it might be better to specify rules for phone number from common country (e.g. min 3- 15 phone numbers total number)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: CJ-783/ped#10

### LINKED ISSUE #209: [PE-D][Tester D] Inconsistent error message for invalid index
Both negative index and too big index should fall under "index out of range", but they give very different warning message.

Another related issue: Currently the description for `delete` in User Guide only mentioned that negative index is not allowed. it would be good if index that is too big can be mentioned in user guide as a error case as well. Same applies to other commands which use index.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: OvOtter/ped#6

### LINKED ISSUE #210: [PE-D][Tester C] Weird message when show-group-details command is ran
When I ran `show-group-details 1` there were command outputs `seedu.address.model.person..`  and there were `false, false false`.

To recreate this,  I ran `show-group-details 1`.

This will result in confusion from the user as the result is now shown properly

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: CJ-783/ped#11

### LINKED ISSUE #214: [PE-D][Tester D] Find Command is used in examples of Delete command but not mentioned previously
How about introducing the `find` command before `delete` command? Or include an explit reference to the section explaining `find` command?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: OvOtter/ped#7

### LINKED ISSUE #217: [PE-D][Tester A] User Guide: Tag Requirements Not Specified
There is no mention in the User Guide on the requirements of a valid `tag`, though it is stated that any number of tags is supported (for features that support tagging). A reader may not realise that a tag cannot contain spaces, and may attempt to add a tag that contains a space, such as "best friend".

Though this is caught in the app itself, I imagine it could save readers/ users some trouble if it were specified in the user guide somewhere that tags can only be alphanumeric.

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: AerollingOverDeepBlueSeas/ped#7

### LINKED ISSUE #218: [PE-D][Tester B] Attendance not updated when marked
Marked the attendance for Alex Yeoh using "mark-attendance P/Alex Yeoh g/Group 1 w/10", but attendance is not updated in the User Interface.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Ben926/ped#12

### LINKED ISSUE #219: [PE-D][Tester D] User Guide did not mention that duplicated tags will be automatically merged
Command typed: `edit 2 t/hi t/hi`
How about adding a sentence about this behavioural under description of the `add` command?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: OvOtter/ped#8

### LINKED ISSUE #223: [PE-D][Tester A] App: Duplicate Persons Possible Via Name Capitalisation Changes
It is possible to add multiple persons with the same name and details into the list of persons, as long as the capitalisation is changed. In the screenshot below, there are multiple persons with the name Jeff Bezos (just with varying capitalisation) with all other details kept the same, added to the list of persons. This makes it possible for a user to accidentally add a duplicate person without realising it. 

It may help to modify the comparison of persons by name to be case-insensitive. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: AerollingOverDeepBlueSeas/ped#8

### LINKED ISSUE #225: [PE-D][Tester D] Expalanations for examples of Find command can be improved
The wording sounds like a function call instead of a change in GUI. How about "...shows [names] in the current person list"?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: OvOtter/ped#9

### LINKED ISSUE #227: [PE-D][Tester B] Delete-from-group doesn't update UI
I removed Alex Yeoh from Group 1 using "delete-from-group P/Alex Yeoh g/Group 1", and a success output is shown. But Alex Yeoh is still displayed on my screen.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Ben926/ped#15

### LINKED ISSUE #233: [PE-D][Tester E] edit-assignment command allows empty edit
All optional field can be absent when editing an assignment, which is not consistent with other editing commands

-------------
Labels: `type.FeatureFlaw` `severity.VeryLow`
original: Taoseeker/ped#11

### LINKED ISSUE #234: [PE-D][Tester D] Delete Group command has message which includes internal implementation details
In my opinion it is not ideal to show the seedu.address.model.person.Person prefix

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: OvOtter/ped#11

### LINKED ISSUE #235: [PE-D][Tester A] Developer Guide: Ordering of Terms in Glossary
Currently, there appears to be no clear ordering of terms in the glossary. This may make it hard to find a particular term, especially if more terms are included in the glossary. It may be helpful to have some form of ordering to the terms in the glossary (i.e. by alphabetical order, by category, etc), so that readers can find the term they seek clarification about more easily. 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: AerollingOverDeepBlueSeas/ped#10

### LINKED ISSUE #238: [PE-D][Tester B] Assignment Details displayed in output not formatted properly
When using the add-assignment command, the output on the screen is not formatted properly. It is shown in JSON form rather than in a formatted string. Perhaps do away with the field names and the curly braces and only display the information in a user-friendly manner.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Ben926/ped#18

### LINKED ISSUE #241: [PE-D][Tester B] Unmark Attendance not updated
Unmark-attendance command doesnt update the user interface. Here i ran "unmark-attendance P/Bernice Yu g/Group 1 w/1, but although there was a successful output message, the user interface still shows Bernice as attending W1."

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Ben926/ped#19

### LINKED ISSUE #242: [PE-D][Tester D] Names that only differ in upper/lower case can exist at the same time
An easy fix might be to emphasise that names are case-sensitive in the user guide.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: OvOtter/ped#13

### LINKED ISSUE #244: [PE-D][Tester E] Group information not preserved properly after editing the group
Mark week 1 attendance for student dummy in group CS2103T.
The attendance is shown correctly in show-group-details.

Change the group(CS2103T) name to CS2102

The attendance information is missing after editing the group name

It is expected that all information except the edited field should be preserved

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: Taoseeker/ped#12

### LINKED ISSUE #248: [PE-D][Tester B] list-group only shows 3 group members
TAs would want to be able to have a glimpse of their members in the list of groups display, but it only shows 3 members names and a "...and 2 more", despite there being a lot of space for more names to be displayed.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: Ben926/ped#21

### LINKED ISSUE #257: [PE-D][Tester D] All persons are assumed to be a Student when being added to a group
As seen from the user guide, there is no way to specify a role for the person added.

However, in each group, there seems to be different roles. How about removing these roles and considering everyone as a member of the group?

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: OvOtter/ped#17

### LINKED ISSUE #258: [PE-D][Tester D] Mark-attendance is not reflected on GUI
While the message suggests that the command is executed successfully, "Attendance" is still shown as None.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: OvOtter/ped#18

### LINKED ISSUE #259: [PE-D][Tester A] App: Potentially Incorrect Error Message for Adding Person to Blank Group
Currently, when attempting to add a person to a group, but no group is given, the error message is that the group name cannot be alphanumeric.

It may be better to specify that the group name cannot be blank in the error message?

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: AerollingOverDeepBlueSeas/ped#13

### PR DESCRIPTION
**Pull request by zwliew**
**Goal of this PR**: tackle most bug reports labelled as `type.Bug.code` and some labelled as `type.Bug.documentation`.

Preview the UG at: https://zwliew.github.io/tp/UserGuide.html

### Groups
- Fix #210 , fix #234, fix #207
- Fix #174 
- Fix #233 
- Fix #244 
- Fix #193 
- Fix #248
- Fix edit-group only allowing 1 tag

### Group Details
- Display group details as output for any command that modifies a group in any way
- Fix old tags still being shown when displaying group details

### Assignment
- Fix #238

### Attendance
- Fix #258 , fix #218 , fix #241 , fix #199 
- Fix #204 , fix #227 

### Phone
- Fix #208, fix #182

### Indexes
- Fix #209

### Names
- Fix #192 , fix #205 
- Fix #259 

### Tags
- Fix #217

### Documentation
- Semi-fix #191
- Fix #197 , fix #242, fix #223
- Fix #257 
- Fix #225
- Fix #180
- Fix #219
- Fix #173
- Fix #185
- Fix #214
- Fix #179
- FIx #202
- Fix #206
- Fix #176
- Fix #235
- Consolidate common notes about NAME fields in the UG (fixes #183)
- Fix issue where `edit-group` using the same name fails with the "duplicate group" message
- Remove penalty and grade-assignment from the UG (these were functionally removed in #267)
- Describe the expected output of the (un)mark-attendance commands
- Improve formatting by using headers

### Tests
- Add some invalid INDEX tests for EditGroup and DeleteGroup
- Add some tests for ParserUtil.parseGroupName
- Update tests for parsing names to test dashes and slashes

## Further issues we can look at with enough quota
- Allow roles to be specified in `add-to-group` (related to #257)
- More precise validation for phone numbers (related to #180)
- Adding screenshots and sample outputs, especially for unfamiliar commands (related to #196, #201, #194)
- Improve the explanation of the value proposition of the app in the UG

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -26,7 +26,7 @@
  */
 public class ParserUtil {
 
-    public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer.";
+    public static final String MESSAGE_INVALID_INDEX = "Index is not a non-zero unsigned integer!";
```
Comment (dexterkwxn) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:29]: feeling rich hm

**Review by dexterkwxn — APPROVED** [review]
looks good :D
