### PR TITLE
Fix incorrect ui list

### LINKED ISSUE #127: Incorrect list displayed after deleting a person
Reproduction steps:
1. Run `add` to add a person with the name `jensen`
2. `find jensen` to show that one person
3. `delete 1` to delete that one person

Result: the group list ends up being shown.
Expected: the resulting empty filtered list is shown.

### PR DESCRIPTION
**Pull request by lyhthaddeus**
FIxes #127

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java [hunk 1]
```diff
@@ -41,8 +41,8 @@ public CommandResult execute(Model model) throws CommandException {
         }
 
         Person personToDelete = lastShownList.get(targetIndex.getZeroBased());
-        model.deletePerson(personToDelete);
         model.deletePersonFromAllGroups(personToDelete);
+        model.deletePerson(personToDelete);
```
Comment (zwliew) [inline src/main/java/seedu/address/logic/commands/DeleteCommand.java:45]: Thanks for fixing this. Though, the more I think about it, model.deletePerson() should implicitly call model.deletePersonFromAllGroups(), instead of the having the Command call both functions.

In other words: the Command object should only have to interface with the Model object in one way -- by calling Model.deletePerson(). The Model object should handle everything else from that point on.

What do you think?

**Review by zwliew — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/DeleteCommand.java (hunk 1 above)
Comment (lyhthaddeus) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java:45]: Ok that makes sense. I will change it accordingly

Comment (zwliew) [reply src/main/java/seedu/address/logic/commands/DeleteCommand.java:45]: It's ok. I'll leave this for now and fix it later.

**Review by zwliew — APPROVED** [review]
