### PR TITLE
fix(group): Add tags to the EditGroupCommand

### LINKED ISSUE #129: EditGroupCommand does not support tags and has incorrect help message
Example:
```
Invalid command format! 
edit-group: Edits the details of the group identified by the index number used in the displayed group list. Existing values will be overwritten by the input values.
Parameters: INDEX (must be a positive integer) [n/NAME]
Example: edit-group 1 n/CS2103T T12-1 
```

Issues with this output:
- Names must not contain dashes
- No support for tags.

### PR DESCRIPTION
**Pull request by lyhthaddeus**
fixes #129 
regarding the incorrect help message refer to #136 for more details

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddGroupCommand.java [hunk 1]
```diff
@@ -25,9 +28,11 @@ public class AddGroupCommand extends Command {
     public static final String MESSAGE_USAGE = COMMAND_WORD
             + ": Adds a new group to the address book. "
             + "Parameters: "
-            + PREFIX_NAME + "NAME\n"
+            + PREFIX_NAME + "NAME "
+            + "[" + PREFIX_TAG + "TAGS]\n"
             + "Example: " + COMMAND_WORD + " "
-            + PREFIX_NAME + "CS2103T T12-1";
+            + PREFIX_NAME + "CS2103T T12-1"
```
Comment (zwliew) [inline src/main/java/seedu/address/logic/commands/AddGroupCommand.java]: We don't support dashes in group names

```suggestion
            + PREFIX_NAME + "CS2103T T12"
```

**Review by zwliew — CHANGES_REQUESTED** [review]

File: src/main/java/seedu/address/logic/commands/AddGroupCommand.java [hunk 2]
```diff
@@ -36,23 +41,25 @@ public class AddGroupCommand extends Command {
...
     /**
      * Creates an AddGroupCommand to add a new group with the specified name.
      *
      * @param groupName The name of the group to be added.
      */
-    public AddGroupCommand(String groupName) {
+    public AddGroupCommand(String groupName, Set<Tag> tags) {
         requireNonNull(groupName);
         this.groupName = groupName;
+        this.tags = tags;
```
Comment (zwliew) [inline src/main/java/seedu/address/logic/commands/AddGroupCommand.java:55]: We should check that this is non-null

**Review by zwliew — CHANGES_REQUESTED** [review]

**Review by zwliew — APPROVED** [review]
lgtm!

File: src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java [hunk 3]
```diff
@@ -37,8 +37,12 @@ public EditGroupCommand parse(String args) throws ParseException {
             throw new ParseException(String.format(MESSAGE_INVALID_COMMAND_FORMAT,
                     EditGroupCommand.MESSAGE_USAGE), ive);
         }
+        argMultimap.verifyNoDuplicatePrefixesFor(PREFIX_NAME, PREFIX_TAG);
         String newGroupName = argMultimap.getValue(PREFIX_NAME).orElse("");
-        Collection<Tag> tags = ParserUtil.parseTagsForEdit(argMultimap.getAllValues(PREFIX_TAG)).orElse(null);
+        Collection<Tag> tags = null;
+        if (argMultimap.getValue(PREFIX_TAG).isPresent()) {
+            tags = ParserUtil.parseTagsForEdit(argMultimap.getAllValues(PREFIX_TAG)).get();
+        }
```
Comment (zwliew) [inline src/main/java/seedu/address/logic/parser/EditGroupCommandParser.java:45]: We need to set tags to an empty collection if it doesn't exist in the edit command. I'll fix this later
